"""
Telegraph Publisher
====================
Publishes articles to telegra.ph and returns the public URL.
The access token is created on first run and should be saved
in the TELEGRAPH_ACCESS_TOKEN environment variable afterwards.
"""
from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path

import requests

from config import (
    TELEGRAPH_ACCESS_TOKEN,
    TELEGRAPH_AUTHOR_NAME,
    TELEGRAPH_AUTHOR_URL,
)

TELEGRAPH_API = "https://api.telegra.ph"
TOKEN_CACHE   = Path("data/.telegraph_token")


# ── Token management ──────────────────────────────────────────────────────────

def _get_or_create_token() -> str:
    """Return a valid Telegraph access token, creating one if needed."""
    # 1. From env/config
    if TELEGRAPH_ACCESS_TOKEN:
        return TELEGRAPH_ACCESS_TOKEN

    # 2. From local cache file (persists across runs)
    if TOKEN_CACHE.exists():
        return TOKEN_CACHE.read_text().strip()

    # 3. Create a new account
    print("  Creating Telegraph account …")
    resp = requests.post(f"{TELEGRAPH_API}/createAccount", json={
        "short_name":  "PaperDigest",
        "author_name": TELEGRAPH_AUTHOR_NAME,
        "author_url":  TELEGRAPH_AUTHOR_URL,
    }, timeout=10)
    resp.raise_for_status()
    token = resp.json()["result"]["access_token"]

    TOKEN_CACHE.parent.mkdir(exist_ok=True)
    TOKEN_CACHE.write_text(token)
    print(f"  ✅ Telegraph token saved. Add to GitHub Secrets as TELEGRAPH_ACCESS_TOKEN={token}")
    return token


# ── Content builder ───────────────────────────────────────────────────────────

def _md_to_nodes(text: str) -> list[dict]:
    """
    Convert a simple Markdown string to Telegraph Node format.
    Supports: ## headings, **bold** (rendered as strong), blank-line paragraphs.
    """
    nodes = []
    for para in re.split(r"\n{2,}", text.strip()):
        para = para.strip()
        if not para:
            continue
        if para.startswith("## ") or para.startswith("### "):
            tag   = "h4" if para.startswith("### ") else "h3"
            inner = para.lstrip("# ").strip()
            nodes.append({"tag": tag, "children": [_inline(inner)]})
        elif para.startswith("**") and para.endswith("**"):
            nodes.append({"tag": "p", "children": [
                {"tag": "strong", "children": [para.strip("*")]}
            ]})
        else:
            # Split on newlines within the paragraph → multiple inline children
            lines = para.split("\n")
            children = []
            for i, line in enumerate(lines):
                children.append(_inline(line))
                if i < len(lines) - 1:
                    children.append({"tag": "br"})
            nodes.append({"tag": "p", "children": children})
    return nodes


def _inline(text: str):
    """Return a string or a bold node for **...**-wrapped text."""
    # Very simple inline bold support
    if "**" in text:
        parts = re.split(r"\*\*", text)
        children = []
        for i, part in enumerate(parts):
            if not part:
                continue
            if i % 2 == 1:
                children.append({"tag": "strong", "children": [part]})
            else:
                children.append(part)
        return {"tag": "span", "children": children} if len(children) > 1 else children[0]
    return text


def _build_article_nodes(paper: dict) -> list[dict]:
    """Build the full Telegraph article content as a Node list."""
    today = date.today().strftime("%Y年%m月%d日")
    authors = ", ".join(paper.get("authors", [])[:3])
    if len(paper.get("authors", [])) > 3:
        authors += " et al."

    nodes = []

    # Meta info block
    nodes.append({"tag": "p", "children": [
        {"tag": "strong", "children": [
            f"📰 {paper['journal']}  ·  {paper.get('pub_date', today)}"
        ]}
    ]})
    if authors:
        nodes.append({"tag": "p", "children": [f"👥 {authors}"]})
    if paper.get("url"):
        nodes.append({"tag": "p", "children": [
            {"tag": "a", "attrs": {"href": paper["url"]}, "children": ["🔗 查看原文（DOI）"]}
        ]})

    nodes.append({"tag": "hr"})

    # Blog content (Markdown → nodes)
    blog_md = paper.get("blog_content", "")
    if blog_md:
        nodes += _md_to_nodes(blog_md)
        nodes.append({"tag": "hr"})

    # Original abstracts
    nodes.append({"tag": "h3", "children": ["📄 中文摘要"]})
    abstract_zh = paper.get("abstract_zh", "（暂无）")
    nodes.append({"tag": "p", "children": [abstract_zh]})

    nodes.append({"tag": "h3", "children": ["📄 English Abstract"]})
    abstract_en = paper.get("abstract", "(Not available)")
    nodes.append({"tag": "p", "children": [abstract_en]})

    # Footer
    nodes.append({"tag": "hr"})
    nodes.append({"tag": "p", "children": [
        f"🤖 Auto-generated by UTD Paper Daily Digest · {today}"
    ]})

    return nodes


# ── Public API ────────────────────────────────────────────────────────────────

def publish_paper(paper: dict) -> str:
    """
    Publish a paper article to Telegraph.
    Returns the public URL (e.g. https://telegra.ph/Title-05-22).
    """
    token = _get_or_create_token()
    title = paper["title"][:256]  # Telegraph title limit
    nodes = _build_article_nodes(paper)

    try:
        resp = requests.post(f"{TELEGRAPH_API}/createPage", json={
            "access_token":  token,
            "title":         title,
            "author_name":   TELEGRAPH_AUTHOR_NAME,
            "author_url":    TELEGRAPH_AUTHOR_URL,
            "content":       nodes,
            "return_content": False,
        }, timeout=15)
        resp.raise_for_status()
        result = resp.json()
        if not result.get("ok"):
            raise RuntimeError(result)
        url = "https://telegra.ph/" + result["result"]["path"]
        print(f"  ✅ Published: {url}")
        return url
    except Exception as exc:
        print(f"  [ERROR] Telegraph publish failed: {exc}")
        return paper.get("url", "")  # fallback to DOI link
